### ISSUE TITLE
IT keeps loading vae and model  over and over each gen

### ISSUE THREAD

**Issue by 2blackbar** [MMqd/kandinsky-for-automatic1111#3]
This is not good, should be changed

**Comment by MMqd** [comment]
Unloading the Stable Diffusion model saves VRAM. The Stable Diffuson model is loaded back after each generation, in case you want to use it.

Would you prefer buttons to unload and load the Stable Diffusion model at will instead?

**Comment by AugmentedRealityCat** [comment]
> Would you prefer to have buttons to unload and load the Stable Diffusion model, at will, instead?

There are such buttons now directly in the automatic1111-WebUI (in the `DEV` branch at least).

You can access the `Unload SD checkpoint to free VRAM` button (and the button to reload that same model back into VRAM), on the `Actions` page of the `Settings` tab.

![Screenshot 2023-06-14 at 01-03-28 Stable Diffusion](https://github.com/MMqd/kandinsky-for-automatic1111/assets/114955776/3f95eb8c-d00e-4699-943e-ca42dfe39acc)

**Comment by MMqd** [comment]
Added unload/reload buttons.
